spring.application.name=appointment
# appointment_app is a database name
spring.datasource.url=jdbc:mysql://localhost:3306/appointment_app
spring.datasource.username=springuser
spring.datasource.password=1698